version: 2

updates:
  - package-ecosystem: "composer"
    directories:
      - "/services/*"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Composer]"
      prefix-development: "[DEPENDABOT][Composer][Dev]"

  - package-ecosystem: "docker"
    directories:
      - "/services/*"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Docker]"

  - package-ecosystem: "docker-compose"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Docker Compose]"
