version: 2

updates:
  - package-ecosystem: "composer"
    directory: "*"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Composer]"
      prefix-development: "[DEPENDABOT][Composer][Dev]"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/docker/*"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Docker]"
