version: 2

registries:
  purplefy:
    type: composer
    url: https://purplewear.com.br/satispress/
    username: ${{ secrets.PURPLEFY_COMPOSER_USERNAME }}
    password: ${{ secrets.PURPLEFY_COMPOSER_PASSWORD }}

updates:
  - package-ecosystem: "composer"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Composer]"
      prefix-development: "[DEPENDABOT][Composer][Dev]"
  
  - package-ecosystem: "docker"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[DEPENDABOT][Docker]"
