services:
  wp:
    env_file: .env.dev
    restart: 'no'
    ports:
      - '8081:8081'
    entrypoint: []
    command: /var/www/html/wp-content/vendor/bin/wp server --host=0.0.0.0 --port=8081

  nginx:
    image: cgr.dev/chainguard/nginx:latest-dev@sha256:f687438339faa9afcf1ac3e97f2ea37001e6f534e556d550a67879a262aa6088
    restart: 'no'

  mariadb:
    image: cgr.dev/chainguard/mariadb:latest-dev@sha256:1a35eb9fed9a5dc7cd7dcf43ff1237fc6051115b2c72c181fa1e02536590e903
    env_file: .env.dev
    restart: 'no'
