services:
  wp:
    image: ghcr.io/lifeisnphard/purplefy-app:latest-wp-dev
    env_file:
      - .env.dev
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        # Disable plugin and theme update and installation
        define( 'DISALLOW_FILE_MODS', true );
        # Disable automatic updates
        define( 'AUTOMATIC_UPDATER_DISABLED', true );
    restart: 'no'
    volumes:
      - 'document-root:/var/www/html'
    depends_on:
      - mariadb

  nginx:
    image: cgr.dev/chainguard/nginx:latest-dev@sha256:549ad2b1c385cf843bbca3bfc0e6a5533a0cdf0b8d70faf2f3d43c171f4dc9c2
    env_file:
      - .env.dev
    restart: 'no'
    ports:
      - '8080:8080'
    volumes:
      - 'document-root:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - wp

  mariadb:
    image: cgr.dev/chainguard/mariadb:latest-dev@sha256:62523e6bc97843d1e384251644e54247e84c866064e8ac99e4fe1781c8775a38
    env_file:
      - .env.dev
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    restart: 'no'
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'

volumes:
  document-root:
    name: purplefy-app-dev-document-root
    driver: local
  db-data:
    name: purplefy-app-dev-db-data
    driver: local
