services:
  wp:
    env_file: .env
    image: ghcr.io/lifeisnphard/purplefy-app:latest-wp
    build:
      target: wp-prod
      args:
        COMPOSER_ENV: no-dev
    restart: 'always'
  
  nginx:
    image: ghcr.io/lifeisnphard/purplefy-app:latest-nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
      target: nginx-prod
    restart: 'always'
    ports:
      - '8080:8080'
    volumes:
      - 'document-root:/var/www/html'
      - './services/nginx/nginx.conf:/etc/nginx/nginx.conf'
