services:
  wp:
    image: ghcr.io/lifeisnphard/purplefy-app:latest-wp-dev
    env_file:
      - .env.dev
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        # Disable plugin and theme update and installation
        define( 'DISALLOW_FILE_MODS', true );
        # Disable automatic updates
        define( 'AUTOMATIC_UPDATER_DISABLED', true );
    ports:
      - '8080:8080'
    volumes:
      - 'document-root:/var/www/html'
    depends_on:
      - mariadb
    entrypoint: [ ]
    command: /var/www/html/wp-content/vendor/bin/wp server --host=0.0.0.0 --port=8080

  mariadb:
    image: cgr.dev/chainguard/mariadb:latest-dev@sha256:fd2228f470363e428ba70b1c32ba464a3292ddb96797782e973b4b02aad6b7aa
    env_file:
      - .env.dev
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    restart: 'no'
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'

volumes:
  document-root:
    name: purplefy-app-dev-document-root
    driver: local
  db-data:
    name: purplefy-app-dev-db-data
    driver: local
