services:
  wp:
    image: ghcr.io/lifeisnphard/purplefy-app:latest-wp-dev
    env_file: .env.dev
    restart: 'no'
    ports:
      - '8081:8081'
    entrypoint: []
    command: /var/www/html/wp-content/vendor/bin/wp server --host=0.0.0.0 --port=8081

  nginx:
    build:
      target: dev
    restart: 'no'

  mariadb:
    build:
      target: dev
    env_file: .env.dev
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    restart: 'no'
