services:
  wp:
    image: ghcr.io/lifeisnphard/purplefy-app:latest-wp
    env_file: .env
    restart: 'always'

  nginx:
    build:
      target: prod
    restart: 'always'

  mariadb:
    build:
      target: prod
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: 'always'
