name: Trigger auto deployment for purplewear

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ project/purplewear ]
    paths:
    - '**'
    - '.github/workflows/purplewear-AutoDeployTrigger-96bb3d7f-3875-4f14-b705-3f6ab9d7d067.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PURPLEWEAR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PURPLEWEAR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PURPLEWEAR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.PURPLEWEAR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PURPLEWEAR_REGISTRY_PASSWORD }}
          containerAppName: purplewear
          resourceGroup: purplefy-apps-resources
          imageToBuild: ghcr.io/purplewear:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


